[supervisord]
nodaemon=true

[program:nginx]
command=nginx -g "daemon off;"
priority=10

[program:backend]
command=pm2-runtime start src/index.ts --name freshkeep-api
directory=/opt/freshkeep/backend
priority=20
